export const TOKEN_ADDRESS = "<YOUR LOANCOIN TOKEN ADDRESS>";
export const LOAN_ADDRESS = "<YOUR LOANCOIN LOAN CONTRACT ADDRESS>";
export const HYDRA_ADDRESS = "<YOUR HYDRA DATA KEEPER ADDRESS>";
export const API_KEY =  "<YOUR API KEY>"
export const ORACLE_ADDRESS = "<ORACLE ADDRESS>"
export const ORACLE_PASSWORD = "<ORACLE PASSWORD>"
export const IPNS_ADDRESS = "<IPNS ADDRESS>"
